name: urmedio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1 # Note: This requires Dart 3.8, which might not be released yet. Consider using a stable version like ^3.0.0 if you face issues.

# =================================================================
# ✅ CORRECT: ONLY ONE 'dependencies' SECTION ALLOWED
# =================================================================
dependencies:
  flutter:
    sdk: flutter

  # General Dependencies
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.0
  dotted_border: ^3.1.0
  uuid: ^4.5.1
  
  # Firebase & Auth Dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.15.0
  google_sign_in: ^6.1.6
  # google_sign_in_android: ^7.2.1 # Generally not needed when using google_sign_in
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # The assets: line must be indented exactly two spaces under 'flutter:'
  assets:
    # This path includes all files in the assets/images directory.
    - assets/images/